Upgrade node-etcd in monitor-scale to support modern versions of node
The node-etcd package transatively depends on nan, a package that helps
native node packages interface with different versions of the v8
ECMAScript engine. Installations of the monitor-scale dependencies using
node version 10 and up may break due to the following error:

```
no member named 'ForceSet' in 'v8::Object'
```

The installation error may be a nuisance to contributors installing
locally who may not wish to install packages inside a container
environment. (They would have to infer from the monitor-scale Dockerfile
that the project should always run within the boron release of node, aka
node 6.) Assuming that monitor-scale does only support node version 6
and up, the the node-etcd project recommends using its latest release,
v7.